version: '3.5'
services:
  www:
    container_name: ${PREFIX_CONTAINER_NAME}-www
    build:
      context: php
      args:
        - USER=${USER}
        - UID=${UID}
    restart: unless-stopped
    environment:
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
    networks:
       - db
    volumes:
#           - ./app/shared:/var/shared
     - ./app/www:/var/www:cached
     - ./logs:/var/log/
    ports:
     - "${NGINX_PORT}:80"
  db:
    container_name: ${PREFIX_CONTAINER_NAME}-db
    build: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./app/shared:/var/shared
      - ./app/mysql:/var/lib/mysql
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
    restart: unless-stopped
    networks:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - db
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
    restart: unless-stopped
  mailhog:
    image: mailhog/mailhog
    ports:
      - "${MAILHOG_PORT}:8025"
    networks:
      - db
    restart: unless-stopped
#  prerender:
#        container_name: ${PREFIX_CONTAINER_NAME}-prerender
#        build: prerender
#        ports:
#            - "5000:4000"
#        restart: always #auto start prerender after reboot.

#  elasticsearch:
#        container_name: ${PREFIX_CONTAINER_NAME}-elk
#        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.12
#        container_name: ${PREFIX_CONTAINER_NAME}-elasticsearch
#        environment:
#             - node.name=es01
#             - discovery.type=single-node
#             - bootstrap.memory_lock=true
#             - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#        ulimits:
#            memlock:
#              soft: -1
#              hard: -1
#        networks:
#            - elk
#        depends_on:
#            - db
#            - www
#        ports:
#            - 9200
#        volumes:
#            - ./app/elasticsearch:/usr/share/elasticsearch/data
#        restart: unless-stopped

#   redis:
#         container_name: ${PREFIX_CONTAINER_NAME}-redis
#         image: redis:5.0-alpine
#         command:
#             - 'redis-server'
#             - '--loglevel ${REDIS_LOGLEVEL:-warning}'
#             - '--databases 2'
#             - '--maxmemory ${REDIS_MAXMEM:-50mb}'
#             - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
#             - '--requirepass ${REDIS_PASS}'
#         ulimits:
#             memlock:
#               soft: -1
#               hard: -1
#         volumes:
#             - ./app/redis:/data
#         ports:
#             - 6379
#         networks:
#             - redis
#         restart: unless-stopped

networks:
    db:
#    elk:
    redis:
#      external: true
#    php:
#      external: true

